---
name: Siriyak
surname: CR
position: "Associate manager clinical Data analyst"
address: "Bangalore Koramagala"
profilepic: "./img/SIRI.jpg"
email: "siriyak2017@gmail.com"
orcid: "77995601256"
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 990000
aboutme: "The Clinical Data Analyst , end to end data programming, testing, data technology, data flow, and data standards, clinical data reports, dashboards and analytics ,as analyst collaborated with the Clinical Data Strategist,and other key stakeholders to deliver standardized reports and innovative analytic solutions for use in global clinical trials,This very CV was even compiled with code"
docname: CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

require(xfun)

packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )

xfun::pkg_attach2(packages, message = FALSE)

source(file = here("r","data.r"))

```

# Employment

```{r EMPLOYMENT}

work %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where
  )

```

# Education

```{r EDUCATION}

edu %>%
  detailed_entries(
    with = inst,
    what = degree,
    # why = detail,
    # when = glue::glue("{startYear} --> {endYear}",.na = ""),
    where = where
  )

```

# Skills

```{r SKILLS}

skills %>%
  detailed_entries(
    with = area,
    what = skills
  )

```


\pagebreak

