

skills <- tribble(
    ~area, ~skills,
    " Statistical -Analytical Skills","Advanced Analytics, Data Analytics, Machine learning Algorithms, SVM, Aprior, KNN, Bayesian Statistics, All Statistical modelling, Computational Statistics, Data Mining, Probabilistic Modelling, Classification, Hidden Markov Models, Predictive Analytics, Statistical Quality control, Exact Test, Time Series Forecasting, Regression Modeling, Credit Scoring, Simulations, Market Basket Analysis Factor Analysis, Discriminant Analysis, Cluster Analysis, Neural Network, Direct marketing, Decision tree, Path analysis, Creating Pivot tables vlookups and developing dashboards",
    "Programming Languages", "R,SAS, basic-Python",
    "Markup Languages", "basic CSS, RMarkdown",
    "other", "Git,RStudio,Sypyder",
    "Microsoft Office", "Excel, Outlook, OneNote, PowerBI, PowerPoint, Word,Power APP,Share Point",
    "IBM Tools-SYSTAT" , "Amos,Text analytics for Survey, SPSS Modeler, Statistics,Basic tableau, Sigmaplot, Sigmastat, Table Curve 2D, Table Curve 3D, Peak fit" ,  
)



edu <- tribble(
    ~degree, ~inst, ~where, 
    "M.S.C In Statiscics", "University of  Mysore", "Mysore",
    "B.S.C in Mathematics, Statistics, Computer Science","Yuvaraj College ,University of Mysore",  "Mysore", 
    # "Post graduate diploma in computer application", "Yuva Shakthi", "Mysore"
)

work <- tribble(
    ~title, ~unit, ~startMonth, ~startYear, ~endMonth, ~endYear, ~where, ~detail,
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore", "LANGUAGES USED --- SAS, RMarkdown, R",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore", "TOOLS USED --- Git, Rshiny,  power BI , Power App,Rs connect",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore", "Programmed and test data reporting dashboarding and analytics for a trial or set of trials within a program using data standards library",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore", "Provide insights into study level deliverables ",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore", "Data Management Plan, Project Plan database  and observed datasets",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore", "Support submission, inspection and regulatory response activities"	,
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore", "Lead large-scale cross Business Unit Theraputic Area projects or programs with high complexity",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore", "Develops and tests new ideas and or applies innovative solutions that create value to the portfolio",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore", "Independently identifies key scientific questions issues and develops solutions to advance the portfolio",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore", "Increase speed accuracy and consistency in the development of reporting and analytic capabilities and deliverables",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore","Partner with Clinical Data Management Associate and Data Strategist to deliver data reporting and analytics per business need",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore","Comply with and influence data standard decisions and strategies for a study and program",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore","Utilize therapeutic knowledge and possess a deep and broad understanding of the technology to develop data reports and analytic solutions",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore","Effectively apply knowledge of applicable internal external and regulatory requirements expectations MQA  CSQ MHRA FDA ICH GCP PhRMA Privacy knowledge etc to all deliverables",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore","Integrates cross-functional and/or external information and applies technical knowledge to data-driven decision making ",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore","Continually seek and implement means of improving processes to reduce data reporting analytics and decrease work effort", 
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore","Represent Data and Analytics processes in cross functional initiatives",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore","Actively participate in shared learning across Data and Analytics organization",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore","Worked to Increase re-usability of reports and analytics",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore","Worked to enable automation and seamless data delivery with real time data validation",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore","Anticipate and resolve key technical operational or business problems that impact the Data and Analytics organization",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore","Interacts with regulators  business partners and outside stakeholders on business issues",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore","Thinks with end to end in mind consistently managing risk to minimize impact on delivery", 
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore","Builds a diverse cross-functional and internal external network to understand how different disciplines and approaches contribute to research and development",
    "Associate Manager Clinical Data Analyst ", "ELILILY and company", "October", 2021, "Present", NA, "Bangalore","Focused on defining analytic solutions to answer scientific questions goals critical success factora and timelines in support of advancing the portfolio", 
    
    "Clinical Data Analyst", "IQVIA", "Feb", 2020, "Oct", 2021, "Bangalore", "LANGUAGES USED ---  RMarkdown, R, MSOffice",
    "Clinical Data Analyst", "IQVIA", "Feb", 2020, "Oct", 2021, "Bangalore", "TOOLS USED --- Git, EXCEL,  RSHINY, Rstudio, SpotFire",
    "Clinical Data Analyst", "IQVIA", "Feb", 2020, "Oct", 2021, "Bangalore", " A good understanding of drug development processes and strategies with proven ability to apply innovative statistical thinking to meet project or business objectives",
    "Clinical Data Analyst", "IQVIA", "Feb", 2020, "Oct", 2021, "Bangalore", " Experience in submissions and interacting with regulatory bodies ICH GCP-Fundamental GCP Exam ",
    "Clinical Data Analyst", "IQVIA", "Feb", 2020, "Oct", 2021, "Bangalore", "Experience of working with  and co-coordinating CROs and Sponsors",
    "Clinical Data Analyst", "IQVIA", "Feb", 2020, "Oct", 2021, "Bangalore", " Experience with modeling and simulation and other innovative methodologies", 
    "Clinical Data Analyst", "IQVIA", "Feb", 2020, "Oct", 2021, "Bangalore","Providing statistical input to the design analysis reporting and interpretation of clinical studies and contribution to publications",
    "Clinical Data Analyst", "IQVIA", "Feb", 2020, "Oct", 2021, "Bangalore","Identifying developing and implementing novel statistical methodologies in support of medicine development", 
    "Clinical Data Analyst", "IQVIA", "Feb", 2020, "Oct", 2021, "Bangalore","Influencing clinical development plans regulatory and commercial strategies", 
    "Clinical Data Analyst", "IQVIA", "Feb", 2020, "Oct", 2021, "Bangalore","Building and maintaining effective strategic working relationships with internal and external Stack Holders to meet business needs",
    "Clinical Data Analyst", "IQVIA", "Feb", 2020, "Oct", 2021, "Bangalore","Providing technical advice mentoring and training", 
    "Clinical Data Analyst", "IQVIA", "Feb", 2020, "Oct", 2021, "Bangalore","Validating analysis output based on  relevant SOPs  Guidances",
    "Clinical Data Analyst", "IQVIA", "Feb", 2020, "Oct", 2021, "Bangalore","Keeping   up to date with current literature and may research new methodologies", 
    "Clinical Data Analyst", "IQVIA", "Feb", 2020, "Oct", 2021, "Bangalore","Managing conflicting demands and priorities", 
    "Technical consultant Statistician Data analyst  ", "SPSS South Asia private limited ", "June", 2017, "Feb", 2020, "Bangalore", "Used data visualization statistical analysis pattern recognition, and machine learning",
    "Technical consultant Statistician Data analyst  ", "SPSS South Asia private limited ", "June", 2017, "Feb", 2020, "Bangalore","along with domain knowledge and subject specific models to solve science engineering and commercial problems",
    "Technical consultant Statistician Data analyst  ", "SPSS South Asia private limited ", "June", 2017, "Feb", 2020, "Bangalore","Assisted the formulation of new projects or enhancements of existing models", 
    "Technical consultant Statistician Data analyst  ", "SPSS South Asia private limited ", "June", 2017, "Feb", 2020, "Bangalore","Contribute to all stages of data analytics or decision modeling development deployment  and support", 
    "Technical consultant Statistician Data analyst  ", "SPSS South Asia private limited ", "June", 2017, "Feb", 2020, "Bangalore","Database historian development data extraction transformation data filtering and quality control", 
    "Technical consultant Statistician Data analyst  ", "SPSS South Asia private limited ", "June", 2017, "Feb", 2020, "Bangalore","exploratory data analysis and visualization  and programming with an emphasis on scripting languages",
    "Technical consultant Statistician Data analyst  ", "SPSS South Asia private limited ", "June", 2017, "Feb", 2020, "Bangalore","Processed unstructured data into a form suitable for analysis",
    "Technical consultant Statistician Data analyst  ", "SPSS South Asia private limited ", "June", 2017, "Feb", 2020, "Bangalore","Created tutorials documentation training material and case studies",
    "Technical consultant Statistician Data analyst  ", "SPSS South Asia private limited ", "June", 2017, "Feb", 2020, "Bangalore","Built simulation models using proprietary and vendor tools to model business problems" , 
    "Technical consultant Statistician Data analyst  ", "SPSS South Asia private limited ", "June", 2017, "Feb", 2020, "Bangalore","Analyze simulation results and develop technical reports and presentations", 
    "Technical consultant Statistician Data analyst  ", "SPSS South Asia private limited ", "June", 2017, "Feb", 2020, "Bangalore","Supervised the Predictive Analytics of developers  during ongoing project for writing time series algorithm  R integration Survival Analysis  and validated the output" ,
    "Pre sales  Post sales Technical Associate Statistician  ", "Starcom information Technology limited ", "May", 2016, "April", 2017, "Bangalore",  "Actively involved in proposal elaboration client presentations and business development activities",
    "Pre sales  Post sales Technical Associate Statistician  ", "Starcom information Technology limited ", "May", 2016, "April", 2017, "Bangalore","Creating  Business presentations Technical documents Case studies and other collateral's for respective Verticals" ,
"Pre sales  Post sales Technical Associate Statistician  ", "Starcom information Technology limited ", "May", 2016, "April", 2017, "Bangalore", "Maintaining excellent relations with key clients business groups to generate referrals as well as build avenues for additional business Planning and Implementing Promotional Activities to create Brand Visibility and Penetrate Market",
# "Pre sales  Post sales Technical Associate Statistician  ", "Starcom information Technology limited ", "May", 2016, "April", 2017, "Bangalore","Improved efficiency by developing written guidelines for various processes including documentation requirements ",
"Pre sales  Post sales Technical Associate Statistician  ", "Starcom information Technology limited ", "May", 2016, "April", 2017, "Bangalore","Streamlined training processes through the creation of quick reference to clients work efficiency prospecting",
"Pre sales  Post sales Technical Associate Statistician  ", "Starcom information Technology limited ", "May", 2016, "April", 2017, "Bangalore","Stakeholder management coordinating and working with cross functional teams and departments to fetch relevant and required information",
"Pre sales  Post sales Technical Associate Statistician  ", "Starcom information Technology limited ", "May", 2016, "April", 2017, "Bangalore","Delivered solutions-driven customer service in multiple roles leveraging a natural ability to build rapport, assess needs and determine best practices to solve problems and meet needs for people of all ages and positions",
# "Pre sales  Post sales Technical Associate Statistician  ", "Starcom information Technology limited ", "May", 2016, "April", 2017, "Bangalore","Combines comprehensive understanding of organizational policies and processes with detailed listening skills to provide creative and immediate conflict resolution"  ,
    "Pre sales  Post sales Technical Associate Statistician  ", "Starcom information Technology limited ", "May", 2016, "April", 2017, "Bangalore","Supervised the StarBI team of developers  during ongoing project for writing time series algorithm  R integration and validated the output",
    "Pre sales  Post sales Technical Associate Statistician  ", "Starcom information Technology limited ", "May", 2016, "April", 2017, "Bangalore" ,"Used Statistical techniques for hypothesis testing to validate data and interpretations",
    "Pre sales  Post sales Technical Associate Statistician  ", "Starcom information Technology limited ", "May", 2016, "April", 2017, "Bangalore","Performed market analysis to efficiently achieve objectives increasing sales" ,
    "Pre sales  Post sales Technical Associate Statistician  ", "Starcom information Technology limited ", "May", 2016, "April", 2017, "Bangalore","Successfully interpreted data to draw conclusions for managerial action and strategy Presented findings and data to team to improve strategies and operations",
)


